base/Dockerfile
base/prepare.sh
notebook/Dockerfile

See https://github.com/dask/dask-docker/issues/4 and https://github.com/kubernetes/charts/issues/2912
cc @danielfrg also @ogrisel

Add conda and pip packages at run time

---

docker-compose.yml
notebook/Dockerfile
notebook/prepare.sh

The docker-hub build of the notebook image was failing due to a missing prepare.sh file.  For the short-term I've just copied over the file from base/ to notebook/ .  If there are cleaner ways to accomplish this I'd be glad for someone to fix this.
I've also added the bokeh diagnostic page ports to the docker-compose file

Fix notebook build

---

base/Dockerfile
notebook/Dockerfile

This also does the following:
1.  Removes fastparquet and numba
2.  Adds python-blosc, not just blosc
3.  Adds graphviz
4.  Adds example notebooks

Update images to dask 0.17.0

---

base/Dockerfile
base/prepare.sh

The use of a virtual environment here might not be necessary (we don't expect users to make many conda environments within a docker container) and it can be confusing.  See https://gitter.im/dask/dev?at=5ac66b7d1130fe3d36a6dcdb
cc @yuvipanda
I haven't tested this yet.

Use root environment in base docker image

---

base/Dockerfile
notebook/Dockerfile

The two Dockerfiles of this repo where not updated in sync.
BTW, how are the docker images pushed to dockerhub and how is the tag of the image selected? Manually?

Bump versions to distributed 1.21.4

---

base/prepare.sh

For most users this won't make a difference, but users that use bash -c "<multiple commands>" at docker run there are important differences, namely it doesn't work without the quotes.
example of the difference:
test.sh:
>echo $@
>$@
>echo "$@"
>"$@"
$ bash test.sh bash -c "echo hello world; echo `pwd`"
>bash -c echo hello world; echo /home/joran
>
>bash -c echo hello world; echo /home/joran
>hello world
>/home/joran

fixed prepare.sh to avoid certain bugs

---

notebook/examples/03-dataframes-timeseries.ipynb

Fixes #40 
Re-built container with `docker-compose up --build` after making the change to the notebook, and tested by running through the notebook again.

update example03 to account for pandas.rolling() difference in v0.23.x

---

notebook/examples/05-nyc-taxi.ipynb
notebook/examples/06-nyc-parquet.ipynb

This gets-around issue where the default behaviour includes looking for GCE credential, which
fails when nor running on GCE.
See also https://github.com/dask/gcsfs/pull/144 which would remove the 'cloud' credentials search, making this change purely defensive.
This did not solve all Dask processing problems for me when running these examples in Docker containers.  You also need to run a script to install `gcsfs` on all worker nodes and notebook, and then there are some scale issues.  But it does allow the remote data to be read anonymously.

Added token='anon' and {'token': 'anon'} to gcsfs calls to public buckets

---

base/prepare.sh
notebook/prepare.sh

Container launch was hanging on a "y/N" prompt from `conda`, so I added the '-y' flag to `conda install` command in both `prepare.sh` scripts.

added '-y' flag to  command

---

ci/deploy.sh

Removing some bad copy pasta here. I had left it as tagging dev images with the commit hash, but should just be the `dev` tag.

Fix dev tags

---

.gitattributes

Possible fix for #38 
Issue
-----
Cloning a repository with git for windows will checkout files with CRLF line endings instead of LF. This behavior breaks running the container normally.
Error Message
----------------
```
[FATAL tini (7)] exec /usr/bin/prepare.sh failed: No such file or directory
```
Reproduce
------------
1. Clone the dask-docker repo on windows.
```
git --version
git version 2.16.0.windows.2
```
2. Build.
```
cd dask-docker
docker build --tag dask base/.
```
3. Run with `docker run dask dask-scheduler`
Fix
---
Use a .gitattributes to force the right line endings for certain files. In this case, we just need bash files to  use 'LF' line endings. [See more documentation here.](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings)

Use .gitattributes to configure line endings

---

README.md

I followed original link and saw that https://github.com/helm/charts/tree/master/stable/dask-distributed is Deprecated.

DOC: Point to dask Helm Chart instead of dask-distributed

---

notebook/examples/ml/sklearn-joblib.ipynb

`dask_ml.joblib `has been removed. This will use `joblib.parallel_backend` now.

Fix joblib import error

---

.github/workflows/watch-conda-forge.yml

Update the GitHub Action for getting the latest anaconda package version. This now sorts semver package tags correctly.

Update Action version

---

.github/workflows/watch-conda-forge.yml

The Create Pull Request Action seems to have broken due to an upstream dependency issue.
Upgrading the action to `v2` should resolve.

Update Create Pull Request Action to v2

---

ci/deploy.sh

In https://github.com/dask/dask-docker/pull/89 we added a `jupyter/base-notebook:lab` image to `docker-compose.yml`. This leads to failures when we run our current deploy script (xref https://travis-ci.com/github/dask/dask-docker/builds/167524093#L2450-L2451). 
This PR changes our deploy script to only tag and push images in the `daskdev` organization. 
cc @jacobtomlinson

Only deploy daskdev images

---

notebook/Dockerfile
notebook/prepare.sh

This attempts to resolve #59 
I realized that changing the order of statements at the end of the Dockerfile wasn't going to solve the problem. However, moving the command that launches the Jupyter server from the container image itself into the prepare script called by the entry point seems to fix this in my local testing. I do now run into [other issues](https://github.com/sudo-project/sudo/issues/42) but they are minor and apparently unrelated.
Following the [testing guidelines](https://github.com/dask/dask-docker#how-to-use--test) I see a version mismatch warning between scheduler and workers, but that was there before my change and the rest of the output seems as expected:
```python
/opt/conda/lib/python3.8/site-packages/distributed/client.py:1136: VersionMismatchWarning: Mismatched …
```

EXTRA_APT_PACKAGES permission errors in notebook image

---

notebook/Dockerfile

The previous generic tag "lab" no longer exists.
Now we use "lab-2.2.5"

Update JupyterLab tag

---

.github/workflows/watch-conda-forge.yml

GitHub Actions made some breaking changes so bumping the `peter-evans/create-pull-request` action to fix. 
Added the extra `author` option as per the [upgrading docs](https://github.com/peter-evans/create-pull-request/blob/master/docs/updating.md#updating-from-v2-to-v3).

Update auto PR action

---

notebook/examples/ml/sklearn-joblib.ipynb

`iid` parameter was removed from `GridSearchCV` in Scikit-learn 0.24

Remove iid parameter in GridSearchCV

---

notebook/examples/ml/sklearn-joblib.ipynb

Since it sounds like scikit-learn has already made this change ( https://github.com/dask/community/issues/68#issuecomment-767084497 ) and the URL seems to work fine
cc @jrbourbeau

Use `main` branch from scikit-learn

---

notebook/Dockerfile

When updating to Dask 2021.02.0 in https://github.com/dask/dask-docker/pull/141 CI has begun to fail due to an old version of `nodejs` being installed (see https://travis-ci.com/github/dask/dask-docker/builds/216299408#L2249). This PR updates our notebook image to JupyterLab 3 to help streamline our JupyterLab extension installation process.

JupyterLab 3

---

README.md
docker-compose.yml

This was erroneously added in https://github.com/dask/dask-docker/commit/2f4b7bf37707a094388e7a80103b2106ff37cdf1. I suspect I was messing around locally and accidentally committed these changes. This PR removes `EXTRA_PIP_PACKAGES` pointing to dev dask and also removes the `-a` option from `git commit` in our release instructions to help prevent this type of thing from happening in the future. 
cc @jacobtomlinson 
Closes https://github.com/dask/dask-docker/issues/146

Remove EXTRA_PIP_PACKAGES pointing to dev dask

---

README.md
notebook/prepare.sh

Added support for a JUPYTERLAB_ARGS environment variable
Also addressed an issue with notebook prepare.sh script
that caused it to prematurely drop to a bash terminal prior to
launching the juputer lab instance
Addresses #124

Support JUPYTERLAB_ARGS

---

notebook/Dockerfile

Add the Kubectl binary to the Dask Jupyter image.
Useful for scaling workers up and down in the Dask Helm Chart.

Add kubectl

---

base/Dockerfile
notebook/Dockerfile

Closes #164 
Looks like `dask-examples` CI is failing on `main` anyway so let's bump here and then try to fix CI over there after.

Bumpy numpy==1.21.1 pandas==1.3.0

---

README.md
build/docker-compose.yml
docker-compose.yml

I've shuffled the README around a little to make things clearer and added badges and links to the images on Docker Hub.
The `docker-compose.yml` that is used for building has also grown in complexity over time and I've seen users get confused and try and use that stack for running Dask instead of building it. To solve this I've moved the building stack into a `build` directory and created a new simplified example stack in the root of the project.

Refactor README and make example cleaner

---

.github/workflows/build.yml
README.md

Looks like in #149 the `daskdev/dask-notebook` image got accidentally renamed to `daskdev/notebook`.
I've fixed the images on Docker Hub manually and this PR puts things right for next time.

dask-notebook for accidentally renamed to just notebook

---

base/Dockerfile

I think by setting something like `python==3.8` we are getting `3.8.0`. If we set `python=3.8` we will get the latest patch release (currently `3.8.10`).
Also adding blosc.
Hopefully this will address the warning in #161.

Losely pin Python and add blosc

---

.github/workflows/build.yml

https://github.com/dask/dask-docker/pull/178 updated the `release: XXXX.XX.X` field in `build/docker-compose.yml` but not `.github/workflows/build.yml`. This PR updates `.github/workflows/build.yml` accordingly.

Bump to 2021.8.1 in docker build workflow

---

notebook/prepare.sh

Some spawning environments such as [the one used in Kubeflow](https://www.kubeflow.org/docs/components/notebooks/container-images/#image-requirements) expect to set an `NB_PREFIX` environment variable when proxying the Jupyter server so that Jupyter handles requests correctly.
Updating the `jupyter lab` command to handle this.

Handle NB_PREFIX

---

.github/workflows/build.yml
README.md
base/Dockerfile
build/docker-compose.yml

The last package is building on conda-forge shortly, so I figured I'd put this up.

Update Dask version to 2022.2.1

---

.github/workflows/build.yml
README.md
build/docker-compose.yml
docker-compose.yml

Closes #177.
This PR updates the build CI to publish images to the GitHub Container Registry in addition to Docker Hub.
It also updates the documentation to mention the `ghcr.io` images by default as part of the deprecation of Docker Hub. Eventually we may choose to remove Docker Hub all together.
I have already manually pushed the `2022.2.1` images to `ghcr.io` so folks can get started with them right away.

Add ghcr.io builds

---

base/Dockerfile
notebook/Dockerfile

Numpy and Pandas have been pinned in the docker images for a long time. Given that we pin the Dask version I would hope that conda can resolve this correctly and we shouldn't need further pinning. Given some issues raised by @charlesbluca I'm keen to unpin here.
cc @dask/maintenance  for thoughts

Unpin dependencies

---

.github/workflows/autotag.yml

xref #180
I noticed in the `2022.3.0` release the tag was not created. I think this was because the autotag action is broken and @jrbourbeau has been manually creating the tag. This PR should fix up the action so that it works as expected.
cc @jsignell

Fix autotag action

---

.github/workflows/build.yml

In #207 I missed the step to log into the GitHub Container Registry. Adding this here.

Log into GitHub Container registry

---

.github/workflows/autotag.yml

We have an actions workflow to automatically build and push images when tags are created. However this doesn't get triggered when the tag is created by a workflow using the `GITHUB_TOKEN` so switching this to the `DASK_BOT_TOKEN` too.

Use bot token for autotagging

---

.github/workflows/build.yml

With #214, we accidentally made it so images would not be built/published on new/updated tags.
This PR add the `on.push.tags` condition to the image building workflow so this is no longer the case.

Trigger images builds on tag pushes

---

base/Dockerfile
notebook/Dockerfile

Since our `dask-notebook` images are already running with a Mambaforge installation, I figured we could make this consistent in the `dask` images and remove all uses of `conda` since we no longer need to install `mamba`.

Always use `mamba` for conda installs in Dockerfiles

---

.github/workflows/build.yml

This PR makes it so that all commits to `main` will publish the following images:
- `dev-py<py_version>` - images built using the latest source, with `python=$py_version`
- `dev` - alias for the `dev-py<py_version>` corresponding to the `defaultpython` set in the Docker build workflow
Closes #223

Publish to `dev` tag on all commits

---

README.md

Closes #236 
To build the base notebook image we are building from a git repo that uses a subdirectory. Sadly `buildkit` still doesn't support this despite now being the default builder, so updating the instructions here to continue using the legacy builder.
_Note that we don't use these instructions for building in CI, this only affects users building locally._

Disable buildkit when building images

---

.github/workflows/build.yml
build/docker-compose.yml

Recently `jupyter/docker-stacks` switched the name of their default branch to `main` (xref https://github.com/jupyter/docker-stacks/pull/1741). This PR makes the corresponding update here so we don't encounter `git` fetch errors like we were seeing in [this CI build](https://github.com/dask/dask-docker/runs/7260101545?check_suite_focus=true)

Use `main` branch with `jupyter/docker-stacks`

---

.github/workflows/build.yml
build/docker-compose.yml
notebook/fix-upstream-jupyter.patch

Not sure how close we are to resolution in https://github.com/jupyter/docker-stacks/issues/1810, so this PR attempts to resolve the issue locally by patching the impacted `base-notebook` Dockerfile to update `mamba` before proceeding with the build.

Patch upstream `base-notebook` Dockerfile to resolve mamba issues

---

.github/workflows/build.yml
README.md
build/docker-compose.yml
notebook/Dockerfile

A new Dask version has been detected.
Updated Dockerfiles to use `2022.11.0`.
Also modified our notebook images / build process to now derive from `docker-stacks-foundation` to account for https://github.com/jupyter/docker-stacks/pull/1825.

Update Dask version to 2022.11.0, switch from `base-notebook` to `docker-stacks-foundation`

---

.github/workflows/build.yml

We have support for Python 3.11 now, so let's add corresponding docker images 
cc @charlesbluca @jacobtomlinson

Add Python 3.11 images

---

.github/workflows/build.yml

Installing things from GitHub releases has been flaky recently due to frequent API outages. Added retry flags suggested by @jrbourbeau. 
This tells curl to retry every 10 seconds for one minute. 
Closes #280

Retry installing Container Canary

---

.github/workflows/autotag.yml

A possible temporary workaround as suggested in https://github.com/ButlerLogic/action-autotag/issues/46 and https://github.com/ButlerLogic/action-autotag/issues/45#issuecomment-1825726927
cc @hendrikmakait @jacobtomlinson @charlesbluca

Pin `butlerlogic/action-autotag` to 1.1.2 release

---

.github/workflows/build.yml

xref https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Avoid deprecated ``set-output``

---

notebook/Dockerfile
notebook/prepare.sh

Currently, the `dask-notebook` container starts Jupyter during the `ENTRYPOINT` and never executes the `CMD`.
You may want to do something like `dask scheduler --jupyter ...` instead of `jupyter lab ...` but that is not possible right now. This change moves the Jupyter command into the `CMD` which allows overriding at runtime.

Allow overriding the notebook command

---

.github/workflows/watch-conda-forge.yml

I fixed up some issues in `jacobtomlinson/gha-anaconda-package-version`. This PR bumps to the latest release here.

Bump to the latest release of jacobtomlinson/gha-anaconda-package-version

---

base/Dockerfile
notebook/Dockerfile

Resolves #338 using recommended as given by `mamba` documentation to stop hanging builds. (See issue for more details on issue)
By exporting `G_SLICE=always-malloc` before calling Mamba
Builds currently have a random chance of hanging forever (see: https://github.com/dask/dask-docker/actions/runs/12659677038/job/35279267366)

Patch issue with hanging docker builds on arm64 builds
