dask/dask-docker

notebook/Dockerfile

Use tini in dask-notebook

---

base/prepare.sh

Add option to add debian packages

---

notebook/prepare.sh

Add option to add debian packages in notebook

---

base/Dockerfile
notebook/Dockerfile

Bump dask to 0.18.1

---

notebook/Dockerfile

Install server-side component of dask-labextension

---

notebook/Dockerfile

https://www.npmjs.com/package/dask-labextension
cc @mrocklin

Use published version that exists

---

base/Dockerfile
notebook/Dockerfile

Bump Dask to `2.3.0` and labextension to `1.0.3`

Bump dask version and labextension version

---

base/Dockerfile
notebook/Dockerfile

Also updates `numpy==1.17.2` and `pandas==0.25.2`
Closes #62 and closes https://github.com/dask/distributed/issues/3167

Bump to dask 2.6.0

---

base/Dockerfile
notebook/Dockerfile

Added lz4 to Dockerfile as suggested in #66

adding lz4 to Dockerfiles

---

base/Dockerfile
docker-compose.yml
notebook/Dockerfile

Use Python 3.8

---

.travis.yml
README.md

xref https://github.com/dask/community/issues/68

Updates for new main default branch

---

base/Dockerfile
notebook/Dockerfile

Closes #43.
It's been a couple of years since that issue was opened so I'm not sure if this is still desirable. But thought I'd get it in anyway.

Add cachey and streamz

---

.github/workflows/autotag.yml

Fix autotag regex

---

.github/workflows/watch-conda-forge.yml

This is a follow-up to https://github.com/dask/dask-docker/pull/179 and part of https://github.com/dask/dask-docker/issues/180

Update `watch-conda-forge` include regex

---

README.md

Update README badges for 2021.8.1 release

---

build/docker-compose.yml

Set args properly in build docker-compose

---

.github/workflows/watch-conda-forge.yml

xref: https://github.com/dask/dask-docker/pull/194#issuecomment-962985426

Add `README.md` to watchlist

---

.github/workflows/build.yml
README.md
build/docker-compose.yml

Updating `Dockerfile`s to use `2022.2.0`.

Update Dask version to 2022.2.0

---

.github/workflows/build.yml

Limit push CI trigger to main branch

---

.github/workflows/build.yml

Closes #248 
Add `latest-py3.8`, `latest-py3.9`, `latest-py3.10` labels which get bumped with each release.

Add ghcr.io/dask/dask:latest-pyXX tags

---

.github/workflows/build.yml
README.md
build/docker-compose.yml

Currently blocked by the Dask conda-forge release

Release 2022.10.2

---

.github/workflows/watch-conda-forge.yml

Update auto-update workflow to target all files

---

.github/workflows/build.yml
README.md
base/Dockerfile
build/docker-compose.yml

Make Python 3.10 the default and drop 3.8

---

.github/workflows/watch-conda-forge.yml

Add button for running conda-forge watching job

---

.github/workflows/build.yml
notebook/Dockerfile

Add Python 3.12 images

---

.github/workflows/build.yml

Updated build CI to include arm64 images. Also updated workflow steps to latest versions.

Add arm64 builds

---

base/prepare.sh
notebook/prepare.sh

Prepare script should exit on errors
